### ISSUE TITLE
Missing insertItems in PaperScope.settings

### ISSUE THREAD

**Issue by lexa274** [clark-stevenson/paper.d.ts#20]
I've noticed that property insertItems: boolean is missing from settings object in PaperScope class. And another thing - shouldn't the Path.Rectangle's first constructor be defined like this:

constructor(rectangle: paper.Rectangle, radius?: number);

instead of this:

constructor(rectangle: Rectangle, radius?: number);

**Comment by clark-stevenson** [comment]
Hey @lexa274 sorry for the delay on this. 

Almost 4 years ago I wrote this for a project which was never started and since then, has not been maintained much other than some pull requests.  It is atleast 2 versions outdated. 

If you use paper regularly, I would encourage you to adapt the types, and make a PR at DefinitelyTyped.

 `https://www.npmjs.com/package/@types/paper`

I am not qualified to do so so appologies I cannot be more help 😞 

I will archive this straight away to avoid any one else confusion and thanks for chipping in anyway 🍻
